sudo: false
language: python

python:
- 2.7

addons:
  postgresql: "9.4"

install:
- make -f config/travis .build/dev-requirements.timestamp
- make -f config/travis install

before_script:
- echo "create user \"www-data\" with password 'www-data;'" | psql -U postgres
- PGUSER=postgres USER=travis scripts/create_user_db_test.sh

script:
- make -f config/travis check

notifications:
  email: false
