sudo: false
language: python

python:
- 3.4

addons:
  postgresql: "9.4"

services:
- elasticsearch

install:
- make -f config/travis .build/dev-requirements.timestamp
- make -f config/travis install

before_script:
- echo "create user \"www-data\" with password 'www-data;'" | psql -U postgres
- PGUSER=postgres USER=travis scripts/create_user_db_test.sh
- curl http://localhost:9200/

script:
- make -f config/travis check

notifications:
  email: false
