api:
  image: 'docker.io/c2corg/v6_api:latest'
  ports:
    - 6543:6543
  environment:
    db_host: 'postgresql'
    elasticsearch_host: 'elasticsearch'
    redis_url: 'redis://redis:6379/'
    version: ''
  volumes:
    - ./c2corg_api:/var/www/c2corg_api
  command: make -f config/docker serve
  links:
    - postgresql
    - elasticsearch
    - redis

postgresql:
  image: 'docker.io/c2corg/c2corg_pgsql:anon-2018-11-02'
  environment:
    PGDATA: '/c2corg_anon'
  volumes:
    - docker-compose/pgsql-settings.d/:/c2corg_anon/pgsql-settings.d/
  ports:
    - 5432:5432

elasticsearch:
  image: 'docker.io/c2corg/c2corg_es:anon-2018-11-02'
  ports:
    - 9200:9200
  command: -Des.index.number_of_replicas=0 -Des.path.data=/c2corg_anon

redis:
  image: 'docker.io/redis:3.2'
  ports:
    - 6379:6379
